import {state,role,can} from "../core/state.js";
import {escapeHtml,formatDate} from "../utils/dom.js";
import {equipmentTable,requestTable,auditList} from "../components/tables.js";
import {borrowingRequestForm} from "../components/forms.js";
export const pages={
dashboard(){const e=state.data.equipment,r=state.data.requests;return `<div class="stats"><div class="stat"><small>TOTAL EQUIPMENT</small><span class="num">${e.length}</span><small>Registered assets</small></div><div class="stat"><small>PENDING</small><span class="num">${r.filter(x=>x.status==="Pending").length}</span><small>Awaiting administrator review</small></div><div class="stat"><small>BORROWED</small><span class="num">${e.filter(x=>x.status==="Borrowed").length}</span><small>Currently out</small></div><div class="stat"><small>MY REQUESTS</small><span class="num">${r.filter(x=>x.requester_id===state.user.id).length}</span><small>Your submitted requests</small></div></div><div class="grid"><section class="panel"><div class="panel-head"><h3>Recent borrowing activity</h3><button class="small-btn" data-action="goto" data-id="requests">View all</button></div>${requestTable(r.slice(0,7),can("admin","staff"))}</section><section class="panel"><div class="panel-head"><h3>Workflow</h3></div><div class="notice"><b>Pending → Approved / Rejected</b><br><br>If approved: <b>Released → Returned → Closed</b>.<br><br>Equipment under Maintenance cannot be borrowed. Sensitive actions are recorded in the audit trail.</div></section></div>`;},
equipment(){return `<section class="panel"><div class="panel-head"><h3>${can("requester")?"Available equipment":"Equipment inventory"}</h3>${can("admin")?`<button class="small-btn" data-action="new-equipment">+ Add equipment</button>`:""}</div>${can("requester")?`<div class="notice">Only assets marked <b>Available</b> can be requested. Borrowed and Maintenance assets are blocked by the database rules.</div><br>`:""}${equipmentTable(state.data.equipment)}</section>`;},
requests(){const mine=role()==="requester",rows=mine?state.data.requests.filter(x=>x.requester_id===state.user.id):state.data.requests;return `<section class="panel">${can("requester","staff")?`<div class="panel-head"><h3>${role()==="staff"?"Create borrowing transaction":"Submit borrowing request"}</h3></div>${borrowingRequestForm()}<hr>`:""}<div class="panel-head"><h3>${mine?"My requests":"All borrowing requests"}</h3></div>${requestTable(rows,!mine)}</section>`;},
history(){return `<section class="panel"><div class="panel-head"><h3>Request history</h3></div>${requestTable(state.data.requests.filter(x=>x.requester_id===state.user.id),false)}</section>`;},
users(){return `<section class="panel"><div class="panel-head"><h3>User roles</h3></div><div class="notice">Role changes are administrator-only. Database RLS also prevents non-admin users from changing roles.</div><br><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Joined</th><th>Action</th></tr></thead><tbody>${state.data.users.map(u=>`<tr><td>${escapeHtml(u.full_name)}</td><td>${escapeHtml(u.email||"—")}</td><td><span class="status">${escapeHtml(u.role)}</span></td><td>${formatDate(u.created_at)}</td><td>${u.id===state.user.id?"<small>Current user</small>":`<select data-role-user="${u.id}"><option ${u.role==="admin"?"selected":""}>admin</option><option ${u.role==="staff"?"selected":""}>staff</option><option ${u.role==="requester"?"selected":""}>requester</option></select>`}</td></tr>`).join("")}</tbody></table></div></section>`;},
audit(){return `<section class="panel"><div class="panel-head"><h3>Critical action log</h3></div>${auditList(state.data.audit)}</section>`;},
reports(){if(!can("admin"))return `<section class="panel"><div class="empty">Administrator access required.</div></section>`;const e=state.data.equipment,r=state.data.requests,statuses=["Pending","Approved","Rejected","Released","Returned","Overdue","Closed"];return `<div class="stats"><div class="stat"><small>TOTAL EQUIPMENT</small><span class="num">${e.length}</span><small>Registered assets</small></div><div class="stat"><small>ACTIVE BORROWED</small><span class="num">${e.filter(x=>x.status==="Borrowed").length}</span><small>Assets currently released</small></div><div class="stat"><small>MAINTENANCE</small><span class="num">${e.filter(x=>x.status==="Maintenance").length}</span><small>Unavailable assets</small></div><div class="stat"><small>TOTAL TRANSACTIONS</small><span class="num">${r.length}</span><small>Borrowing records</small></div></div><div class="grid"><section class="panel"><div class="panel-head"><h3>Borrowing report</h3></div><div class="table-wrap"><table><thead><tr><th>Status</th><th>Transactions</th></tr></thead><tbody>${statuses.map(status=>`<tr><td><span class="status ${status}">${status}</span></td><td>${r.filter(x=>x.status===status).length}</td></tr>`).join("")}</tbody></table></div></section><section class="panel"><div class="panel-head"><h3>Recent audit activity</h3></div>${auditList(state.data.audit.slice(0,8))}</section></div>`;},
maintenance(){return `<section class="panel"><div class="panel-head"><h3>Maintenance queue</h3></div><div class="notice">Assets under Maintenance are automatically unavailable for borrowing.</div><br>${equipmentTable(state.data.equipment.filter(e=>e.status==="Maintenance"||e.maintenance_note))}</section>`;}
};
